CREATE TABLE IF NOT EXISTS canonical_drugs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  search_name TEXT NOT NULL UNIQUE,
  canonical_name TEXT NOT NULL,
  brand_name TEXT,
  is_brand INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_canonical_search ON canonical_drugs(search_name);
CREATE INDEX IF NOT EXISTS idx_canonical_name ON canonical_drugs(canonical_name);

INSERT OR IGNORE INTO canonical_drugs (search_name, canonical_name, brand_name, is_brand) VALUES
('atorvastatin','Atorvastatin','Lipitor',0),('atorvastatin calcium','Atorvastatin','Lipitor',0),('lipitor','Atorvastatin','Lipitor',1),
('metformin','Metformin','Glucophage',0),('metformin hcl','Metformin','Glucophage',0),('metformin hydrochloride','Metformin','Glucophage',0),('glucophage','Metformin','Glucophage',1),
('levothyroxine','Levothyroxine','Synthroid',0),('levothyroxine sodium','Levothyroxine','Synthroid',0),('synthroid','Levothyroxine','Synthroid',1),('levoxyl','Levothyroxine','Levoxyl',1),
('lisinopril','Lisinopril','Zestril',0),('lisinopril tablets','Lisinopril','Zestril',0),('lisinopril oral tablets','Lisinopril','Zestril',0),('zestril','Lisinopril','Zestril',1),('prinivil','Lisinopril','Prinivil',1),
('amlodipine','Amlodipine','Norvasc',0),('amlodipine besylate','Amlodipine','Norvasc',0),('norvasc','Amlodipine','Norvasc',1),
('metoprolol','Metoprolol','Lopressor',0),('metoprolol succinate','Metoprolol','Lopressor',0),('metoprolol tartrate','Metoprolol','Lopressor',0),('lopressor','Metoprolol','Lopressor',1),('toprol-xl','Metoprolol','Toprol-XL',1),('toprol xl','Metoprolol','Toprol-XL',1),
('omeprazole','Omeprazole','Prilosec',0),('omeprazole magnesium','Omeprazole','Prilosec',0),('prilosec','Omeprazole','Prilosec',1),
('losartan','Losartan','Cozaar',0),('losartan potassium','Losartan','Cozaar',0),('cozaar','Losartan','Cozaar',1),
('albuterol','Albuterol','ProAir',0),('albuterol sulfate','Albuterol','ProAir',0),('proair','Albuterol','ProAir',1),('ventolin','Albuterol','Ventolin',1),
('gabapentin','Gabapentin','Neurontin',0),('neurontin','Gabapentin','Neurontin',1),
('hydrochlorothiazide','Hydrochlorothiazide','Microzide',0),('hctz','Hydrochlorothiazide','Microzide',0),('microzide','Hydrochlorothiazide','Microzide',1),
('sertraline','Sertraline','Zoloft',0),('sertraline hcl','Sertraline','Zoloft',0),('sertraline hydrochloride','Sertraline','Zoloft',0),('zoloft','Sertraline','Zoloft',1),
('montelukast','Montelukast','Singulair',0),('montelukast sodium','Montelukast','Singulair',0),('singulair','Montelukast','Singulair',1),
('pantoprazole','Pantoprazole','Protonix',0),('pantoprazole sodium','Pantoprazole','Protonix',0),('protonix','Pantoprazole','Protonix',1),
('escitalopram','Escitalopram','Lexapro',0),('escitalopram oxalate','Escitalopram','Lexapro',0),('lexapro','Escitalopram','Lexapro',1),
('furosemide','Furosemide','Lasix',0),('lasix','Furosemide','Lasix',1),
('simvastatin','Simvastatin','Zocor',0),('zocor','Simvastatin','Zocor',1),
('clopidogrel','Clopidogrel','Plavix',0),('clopidogrel bisulfate','Clopidogrel','Plavix',0),('plavix','Clopidogrel','Plavix',1),
('bupropion','Bupropion','Wellbutrin',0),('bupropion hcl','Bupropion','Wellbutrin',0),('bupropion hydrochloride','Bupropion','Wellbutrin',0),('wellbutrin','Bupropion','Wellbutrin',1),
('tamsulosin','Tamsulosin','Flomax',0),('tamsulosin hcl','Tamsulosin','Flomax',0),('flomax','Tamsulosin','Flomax',1),
('duloxetine','Duloxetine','Cymbalta',0),('duloxetine hcl','Duloxetine','Cymbalta',0),('cymbalta','Duloxetine','Cymbalta',1),
('carvedilol','Carvedilol','Coreg',0),('coreg','Carvedilol','Coreg',1),
('amoxicillin','Amoxicillin','Amoxil',0),('amoxicillin trihydrate','Amoxicillin','Amoxil',0),('amoxil','Amoxicillin','Amoxil',1),
('rosuvastatin','Rosuvastatin','Crestor',0),('rosuvastatin calcium','Rosuvastatin','Crestor',0),('crestor','Rosuvastatin','Crestor',1),
('prednisone','Prednisone','Deltasone',0),('deltasone','Prednisone','Deltasone',1),
('trazodone','Trazodone','Desyrel',0),('trazodone hcl','Trazodone','Desyrel',0),('trazodone hydrochloride','Trazodone','Desyrel',0),('desyrel','Trazodone','Desyrel',1),
('cyclobenzaprine','Cyclobenzaprine','Flexeril',0),('cyclobenzaprine hcl','Cyclobenzaprine','Flexeril',0),('flexeril','Cyclobenzaprine','Flexeril',1),
('azithromycin','Azithromycin','Zithromax',0),('zithromax','Azithromycin','Zithromax',1),
('meloxicam','Meloxicam','Mobic',0),('mobic','Meloxicam','Mobic',1),
('propranolol','Propranolol','Inderal',0),('propranolol hcl','Propranolol','Inderal',0),('propranolol hydrochloride','Propranolol','Inderal',0),('inderal','Propranolol','Inderal',1),
('venlafaxine','Venlafaxine','Effexor',0),('venlafaxine hcl','Venlafaxine','Effexor',0),('effexor','Venlafaxine','Effexor',1),
('tramadol','Tramadol','Ultram',0),('tramadol hcl','Tramadol','Ultram',0),('tramadol hydrochloride','Tramadol','Ultram',0),('ultram','Tramadol','Ultram',1),
('citalopram','Citalopram','Celexa',0),('citalopram hbr','Citalopram','Celexa',0),('citalopram hydrobromide','Citalopram','Celexa',0),('celexa','Citalopram','Celexa',1),
('pravastatin','Pravastatin','Pravachol',0),('pravastatin sodium','Pravastatin','Pravachol',0),('pravachol','Pravastatin','Pravachol',1),
('hydroxyzine','Hydroxyzine','Vistaril',0),('hydroxyzine hcl','Hydroxyzine','Vistaril',0),('hydroxyzine pamoate','Hydroxyzine','Vistaril',0),('vistaril','Hydroxyzine','Vistaril',1),('atarax','Hydroxyzine','Atarax',1),
('cephalexin','Cephalexin','Keflex',0),('keflex','Cephalexin','Keflex',1),
('glipizide','Glipizide','Glucotrol',0),('glucotrol','Glipizide','Glucotrol',1),
('sitagliptin','Sitagliptin','Januvia',0),('januvia','Sitagliptin','Januvia',1),
('insulin glargine','Insulin Glargine','Lantus',0),('lantus','Insulin Glargine','Lantus',1),
('sildenafil','Sildenafil','Viagra',0),('sildenafil citrate','Sildenafil','Viagra',0),('viagra','Sildenafil','Viagra',1),
('diclofenac','Diclofenac','Voltaren',0),('diclofenac sodium','Diclofenac','Voltaren',0),('voltaren','Diclofenac','Voltaren',1),
('ondansetron','Ondansetron','Zofran',0),('ondansetron hcl','Ondansetron','Zofran',0),('zofran','Ondansetron','Zofran',1),
('finasteride','Finasteride','Proscar',0),('proscar','Finasteride','Proscar',1),('propecia','Finasteride','Propecia',1),
('warfarin','Warfarin','Coumadin',0),('warfarin sodium','Warfarin','Coumadin',0),('coumadin','Warfarin','Coumadin',1),
('lorazepam','Lorazepam','Ativan',0),('ativan','Lorazepam','Ativan',1),
('alprazolam','Alprazolam','Xanax',0),('xanax','Alprazolam','Xanax',1),
('spironolactone','Spironolactone','Aldactone',0),('aldactone','Spironolactone','Aldactone',1),
('potassium chloride','Potassium Chloride','K-Dur',0),('k-dur','Potassium Chloride','K-Dur',1),
('fluticasone','Fluticasone','Flonase',0),('fluticasone propionate','Fluticasone','Flonase',0),('flonase','Fluticasone','Flonase',1),
('insulin aspart','Insulin Aspart','NovoLog',0),('novolog','Insulin Aspart','NovoLog',1),
('insulin lispro','Insulin Lispro','Humalog',0),('humalog','Insulin Lispro','Humalog',1),
('glimepiride','Glimepiride','Amaryl',0),('amaryl','Glimepiride','Amaryl',1),
('pioglitazone','Pioglitazone','Actos',0),('actos','Pioglitazone','Actos',1),
('empagliflozin','Empagliflozin','Jardiance',0),('jardiance','Empagliflozin','Jardiance',1),
('dapagliflozin','Dapagliflozin','Farxiga',0),('farxiga','Dapagliflozin','Farxiga',1),
('semaglutide','Semaglutide','Ozempic',0),('ozempic','Semaglutide','Ozempic',1),('wegovy','Semaglutide','Wegovy',1),
('liraglutide','Liraglutide','Victoza',0),('victoza','Liraglutide','Victoza',1),
('ezetimibe','Ezetimibe','Zetia',0),('zetia','Ezetimibe','Zetia',1),
('allopurinol','Allopurinol','Zyloprim',0),('zyloprim','Allopurinol','Zyloprim',1),
('baclofen','Baclofen','Lioresal',0),('lioresal','Baclofen','Lioresal',1),
('clonazepam','Clonazepam','Klonopin',0),('klonopin','Clonazepam','Klonopin',1),
('valacyclovir','Valacyclovir','Valtrex',0),('valacyclovir hcl','Valacyclovir','Valtrex',0),('valtrex','Valacyclovir','Valtrex',1),
('acyclovir','Acyclovir','Zovirax',0),('zovirax','Acyclovir','Zovirax',1),
('levofloxacin','Levofloxacin','Levaquin',0),('levaquin','Levofloxacin','Levaquin',1),
('ciprofloxacin','Ciprofloxacin','Cipro',0),('ciprofloxacin hcl','Ciprofloxacin','Cipro',0),('cipro','Ciprofloxacin','Cipro',1),
('doxycycline','Doxycycline','Vibramycin',0),('doxycycline hyclate','Doxycycline','Vibramycin',0),('doxycycline monohydrate','Doxycycline','Vibramycin',0),('vibramycin','Doxycycline','Vibramycin',1),
('nitrofurantoin','Nitrofurantoin','Macrobid',0),('nitrofurantoin monohydrate','Nitrofurantoin','Macrobid',0),('macrobid','Nitrofurantoin','Macrobid',1),
('methocarbamol','Methocarbamol','Robaxin',0),('robaxin','Methocarbamol','Robaxin',1),
('pregabalin','Pregabalin','Lyrica',0),('lyrica','Pregabalin','Lyrica',1),
('quetiapine','Quetiapine','Seroquel',0),('quetiapine fumarate','Quetiapine','Seroquel',0),('seroquel','Quetiapine','Seroquel',1),
('aripiprazole','Aripiprazole','Abilify',0),('abilify','Aripiprazole','Abilify',1),
('risperidone','Risperidone','Risperdal',0),('risperdal','Risperidone','Risperdal',1),
('olanzapine','Olanzapine','Zyprexa',0),('zyprexa','Olanzapine','Zyprexa',1),
('haloperidol','Haloperidol','Haldol',0),('haldol','Haloperidol','Haldol',1),
('lamotrigine','Lamotrigine','Lamictal',0),('lamictal','Lamotrigine','Lamictal',1),
('topiramate','Topiramate','Topamax',0),('topamax','Topiramate','Topamax',1),
('levetiracetam','Levetiracetam','Keppra',0),('keppra','Levetiracetam','Keppra',1),
('phenytoin','Phenytoin','Dilantin',0),('phenytoin sodium','Phenytoin','Dilantin',0),('dilantin','Phenytoin','Dilantin',1),
('carbamazepine','Carbamazepine','Tegretol',0),('tegretol','Carbamazepine','Tegretol',1),
('zolpidem','Zolpidem','Ambien',0),('zolpidem tartrate','Zolpidem','Ambien',0),('ambien','Zolpidem','Ambien',1),
('eszopiclone','Eszopiclone','Lunesta',0),('lunesta','Eszopiclone','Lunesta',1),
('temazepam','Temazepam','Restoril',0),('restoril','Temazepam','Restoril',1),
('methylphenidate','Methylphenidate','Ritalin',0),('methylphenidate hcl','Methylphenidate','Ritalin',0),('ritalin','Methylphenidate','Ritalin',1),('concerta','Methylphenidate','Concerta',1),
('amphetamine salts','Amphetamine/Dextroamphetamine','Adderall',0),('amphetamine dextroamphetamine','Amphetamine/Dextroamphetamine','Adderall',0),('adderall','Amphetamine/Dextroamphetamine','Adderall',1),
('atomoxetine','Atomoxetine','Strattera',0),('strattera','Atomoxetine','Strattera',1),
('donepezil','Donepezil','Aricept',0),('donepezil hcl','Donepezil','Aricept',0),('aricept','Donepezil','Aricept',1),
('memantine','Memantine','Namenda',0),('memantine hcl','Memantine','Namenda',0),('namenda','Memantine','Namenda',1),
('oxybutynin','Oxybutynin','Ditropan',0),('oxybutynin chloride','Oxybutynin','Ditropan',0),('ditropan','Oxybutynin','Ditropan',1),
('tolterodine','Tolterodine','Detrol',0),('detrol','Tolterodine','Detrol',1),
('mirabegron','Mirabegron','Myrbetriq',0),('myrbetriq','Mirabegron','Myrbetriq',1),
('solifenacin','Solifenacin','Vesicare',0),('vesicare','Solifenacin','Vesicare',1),
('dutasteride','Dutasteride','Avodart',0),('avodart','Dutasteride','Avodart',1),
('terazosin','Terazosin','Hytrin',0),('hytrin','Terazosin','Hytrin',1),
('alfuzosin','Alfuzosin','Uroxatral',0),('uroxatral','Alfuzosin','Uroxatral',1),
('doxazosin','Doxazosin','Cardura',0),('cardura','Doxazosin','Cardura',1),
('tadalafil','Tadalafil','Cialis',0),('cialis','Tadalafil','Cialis',1),
('vardenafil','Vardenafil','Levitra',0),('levitra','Vardenafil','Levitra',1),
('linaclotide','Linaclotide','Linzess',0),('linzess','Linaclotide','Linzess',1),
('famotidine','Famotidine','Pepcid',0),('pepcid','Famotidine','Pepcid',1),
('esomeprazole','Esomeprazole','Nexium',0),('esomeprazole magnesium','Esomeprazole','Nexium',0),('nexium','Esomeprazole','Nexium',1),
('rabeprazole','Rabeprazole','AcipHex',0),('aciphex','Rabeprazole','AcipHex',1),
('mesalamine','Mesalamine','Asacol',0),('asacol','Mesalamine','Asacol',1),
('methotrexate','Methotrexate','Trexall',0),('trexall','Methotrexate','Trexall',1),
('hydroxychloroquine','Hydroxychloroquine','Plaquenil',0),('hydroxychloroquine sulfate','Hydroxychloroquine','Plaquenil',0),('plaquenil','Hydroxychloroquine','Plaquenil',1),
('apixaban','Apixaban','Eliquis',0),('eliquis','Apixaban','Eliquis',1),
('rivaroxaban','Rivaroxaban','Xarelto',0),('xarelto','Rivaroxaban','Xarelto',1),
('dabigatran','Dabigatran','Pradaxa',0),('pradaxa','Dabigatran','Pradaxa',1),
('oxycodone','Oxycodone','OxyContin',0),('oxycodone hcl','Oxycodone','OxyContin',0),('oxycontin','Oxycodone','OxyContin',1),
('morphine','Morphine','MS Contin',0),('morphine sulfate','Morphine','MS Contin',0),('ms contin','Morphine','MS Contin',1),
('buprenorphine','Buprenorphine','Subutex',0),('subutex','Buprenorphine','Subutex',1),
('naloxone','Naloxone','Narcan',0),('naloxone hcl','Naloxone','Narcan',0),('narcan','Naloxone','Narcan',1),
('naltrexone','Naltrexone','ReVia',0),('revia','Naltrexone','ReVia',1),
('varenicline','Varenicline','Chantix',0),('chantix','Varenicline','Chantix',1),
('cetirizine','Cetirizine','Zyrtec',0),('cetirizine hcl','Cetirizine','Zyrtec',0),('zyrtec','Cetirizine','Zyrtec',1),
('loratadine','Loratadine','Claritin',0),('claritin','Loratadine','Claritin',1),
('fexofenadine','Fexofenadine','Allegra',0),('fexofenadine hcl','Fexofenadine','Allegra',0),('allegra','Fexofenadine','Allegra',1),
('diphenhydramine','Diphenhydramine','Benadryl',0),('diphenhydramine hcl','Diphenhydramine','Benadryl',0),('benadryl','Diphenhydramine','Benadryl',1),
('promethazine','Promethazine','Phenergan',0),('phenergan','Promethazine','Phenergan',1),
('meclizine','Meclizine','Antivert',0),('antivert','Meclizine','Antivert',1),
('epinephrine','Epinephrine','EpiPen',0),('epipen','Epinephrine','EpiPen',1),
('insulin detemir','Insulin Detemir','Levemir',0),('levemir','Insulin Detemir','Levemir',1),
('insulin degludec','Insulin Degludec','Tresiba',0),('tresiba','Insulin Degludec','Tresiba',1),
('glyburide','Glyburide','Diabeta',0),('diabeta','Glyburide','Diabeta',1),
('amiodarone','Amiodarone','Cordarone',0),('cordarone','Amiodarone','Cordarone',1),
('digoxin','Digoxin','Lanoxin',0),('lanoxin','Digoxin','Lanoxin',1),
('isosorbide mononitrate','Isosorbide Mononitrate','Imdur',0),('imdur','Isosorbide Mononitrate','Imdur',1),
('nitroglycerin','Nitroglycerin','Nitrostat',0),('nitrostat','Nitroglycerin','Nitrostat',1),
('hydralazine','Hydralazine','Apresoline',0),('apresoline','Hydralazine','Apresoline',1),
('clonidine','Clonidine','Catapres',0),('catapres','Clonidine','Catapres',1),
('labetalol','Labetalol','Trandate',0),('trandate','Labetalol','Trandate',1),
('bisoprolol','Bisoprolol','Zebeta',0),('zebeta','Bisoprolol','Zebeta',1),
('olmesartan','Olmesartan','Benicar',0),('benicar','Olmesartan','Benicar',1),
('valsartan','Valsartan','Diovan',0),('diovan','Valsartan','Diovan',1),
('irbesartan','Irbesartan','Avapro',0),('avapro','Irbesartan','Avapro',1),
('candesartan','Candesartan','Atacand',0),('atacand','Candesartan','Atacand',1),
('telmisartan','Telmisartan','Micardis',0),('micardis','Telmisartan','Micardis',1),
('colchicine','Colchicine','Colcrys',0),('colcrys','Colchicine','Colcrys',1),
('alendronate','Alendronate','Fosamax',0),('fosamax','Alendronate','Fosamax',1),
('risedronate','Risedronate','Actonel',0),('actonel','Risedronate','Actonel',1),
('ibandronate','Ibandronate','Boniva',0),('boniva','Ibandronate','Boniva',1),
('testosterone','Testosterone','AndroGel',0),('androgel','Testosterone','AndroGel',1),
('estradiol','Estradiol','Estrace',0),('estrace','Estradiol','Estrace',1),
('progesterone','Progesterone','Prometrium',0),('prometrium','Progesterone','Prometrium',1),
('medroxyprogesterone','Medroxyprogesterone','Provera',0),('provera','Medroxyprogesterone','Provera',1),
('clomiphene','Clomiphene','Clomid',0),('clomid','Clomiphene','Clomid',1),
('isotretinoin','Isotretinoin','Accutane',0),('accutane','Isotretinoin','Accutane',1),
('tretinoin','Tretinoin','Retin-A',0),('retin-a','Tretinoin','Retin-A',1),
('adapalene','Adapalene','Differin',0),('differin','Adapalene','Differin',1),
('clindamycin','Clindamycin','Cleocin',0),('cleocin','Clindamycin','Cleocin',1),
('metronidazole','Metronidazole','Flagyl',0),('flagyl','Metronidazole','Flagyl',1),
('sulfamethoxazole trimethoprim','Sulfamethoxazole/Trimethoprim','Bactrim',0),('bactrim','Sulfamethoxazole/Trimethoprim','Bactrim',1),
('fluconazole','Fluconazole','Diflucan',0),('diflucan','Fluconazole','Diflucan',1),
('terbinafine','Terbinafine','Lamisil',0),('lamisil','Terbinafine','Lamisil',1),
('itraconazole','Itraconazole','Sporanox',0),('sporanox','Itraconazole','Sporanox',1),
('oseltamivir','Oseltamivir','Tamiflu',0),('tamiflu','Oseltamivir','Tamiflu',1),
('dextromethorphan','Dextromethorphan','Robitussin',0),('robitussin','Dextromethorphan','Robitussin',1),
('guaifenesin','Guaifenesin','Mucinex',0),('mucinex','Guaifenesin','Mucinex',1),
('lidocaine','Lidocaine','Lidoderm',0),('lidoderm','Lidocaine','Lidoderm',1),
('mupirocin','Mupirocin','Bactroban',0),('bactroban','Mupirocin','Bactroban',1),
('ketoconazole','Ketoconazole','Nizoral',0),('nizoral','Ketoconazole','Nizoral',1),
('benzonatate','Benzonatate','Tessalon',0),('tessalon','Benzonatate','Tessalon',1),
('aspirin','Aspirin','Bayer',0),
('acetaminophen','Acetaminophen','Tylenol',0),('tylenol','Acetaminophen','Tylenol',1),
('ibuprofen','Ibuprofen','Advil',0),('advil','Ibuprofen','Advil',1),('motrin','Ibuprofen','Motrin',1),
('naproxen','Naproxen','Aleve',0),('naproxen sodium','Naproxen','Aleve',0),('aleve','Naproxen','Aleve',1),
('folic acid','Folic Acid','Folvite',0),('folvite','Folic Acid','Folvite',1),
('dexmethylphenidate','Dexmethylphenidate','Focalin',0),('focalin','Dexmethylphenidate','Focalin',1),
('sucralfate','Sucralfate','Carafate',0),('carafate','Sucralfate','Carafate',1),
('sulfasalazine','Sulfasalazine','Azulfidine',0),('azulfidine','Sulfasalazine','Azulfidine',1),
('azathioprine','Azathioprine','Imuran',0),('imuran','Azathioprine','Imuran',1),
('tacrolimus','Tacrolimus','Prograf',0),('prograf','Tacrolimus','Prograf',1),
('mycophenolate','Mycophenolate','CellCept',0),('cellcept','Mycophenolate','CellCept',1),
('enoxaparin','Enoxaparin','Lovenox',0),('lovenox','Enoxaparin','Lovenox',1),
('ketorolac','Ketorolac','Toradol',0),('toradol','Ketorolac','Toradol',1),
('disulfiram','Disulfiram','Antabuse',0),('antabuse','Disulfiram','Antabuse',1),
('levocetirizine','Levocetirizine','Xyzal',0),('xyzal','Levocetirizine','Xyzal',1),
('scopolamine','Scopolamine','Transderm-Scop',0),
('repaglinide','Repaglinide','Prandin',0),('prandin','Repaglinide','Prandin',1),
('canagliflozin','Canagliflozin','Invokana',0),('invokana','Canagliflozin','Invokana',1),
('linagliptin','Linagliptin','Tradjenta',0),('tradjenta','Linagliptin','Tradjenta',1),
('dronedarone','Dronedarone','Multaq',0),('multaq','Dronedarone','Multaq',1),
('ivabradine','Ivabradine','Corlanor',0),('corlanor','Ivabradine','Corlanor',1),
('ranolazine','Ranolazine','Ranexa',0),('ranexa','Ranolazine','Ranexa',1),
('minoxidil','Minoxidil','Loniten',0),('loniten','Minoxidil','Loniten',1),
('guanfacine','Guanfacine','Intuniv',0),('intuniv','Guanfacine','Intuniv',1),
('nebivolol','Nebivolol','Bystolic',0),('bystolic','Nebivolol','Bystolic',1),
('febuxostat','Febuxostat','Uloric',0),('uloric','Febuxostat','Uloric',1),
('dolutegravir','Dolutegravir','Tivicay',0),('tivicay','Dolutegravir','Tivicay',1),
('imatinib','Imatinib','Gleevec',0),('gleevec','Imatinib','Gleevec',1),
('dexmethylphenidate','Dexmethylphenidate','Focalin',0),
('saxagliptin','Saxagliptin','Onglyza',0),('onglyza','Saxagliptin','Onglyza',1),
('lubiprostone','Lubiprostone','Amitiza',0),('amitiza','Lubiprostone','Amitiza',1),
('fentanyl','Fentanyl','Duragesic',0),('duragesic','Fentanyl','Duragesic',1),
('hydrocodone acetaminophen','Hydrocodone/Acetaminophen','Norco',0),('norco','Hydrocodone/Acetaminophen','Norco',1),('vicodin','Hydrocodone/Acetaminophen','Vicodin',1);
