"""
drug_catalog.py
Master drug list for TransparentRx scraping pipeline.
Tiered by prescription volume and clinical significance.

TIER 1 — DAILY   (500 drugs): Top generics by national prescription volume
TIER 2 — WEEKLY  (1500 drugs): Common branded + secondary generics
TIER 3 — MONTHLY (remainder): Specialty, low-volume, niche drugs
"""

# ─────────────────────────────────────────────────────────────────────────────
# TIER 1 — DAILY REFRESH
# Top ~165 drugs × multiple strengths = ~500 unique drug/strength combos
# Source: CMS Top 300 generics by prescription volume
# ─────────────────────────────────────────────────────────────────────────────

TIER_1_DAILY = [
    # Statins
    ("atorvastatin",        "10mg"),
    ("atorvastatin",        "20mg"),
    ("atorvastatin",        "40mg"),
    ("atorvastatin",        "80mg"),
    ("simvastatin",         "10mg"),
    ("simvastatin",         "20mg"),
    ("simvastatin",         "40mg"),
    ("simvastatin",         "80mg"),
    ("rosuvastatin",        "5mg"),
    ("rosuvastatin",        "10mg"),
    ("rosuvastatin",        "20mg"),
    ("rosuvastatin",        "40mg"),
    ("pravastatin",         "20mg"),
    ("pravastatin",         "40mg"),
    ("pravastatin",         "80mg"),
    ("lovastatin",          "20mg"),
    ("lovastatin",          "40mg"),
    ("fluvastatin",         "40mg"),
    ("fluvastatin",         "80mg"),
    # ACE Inhibitors
    ("lisinopril",          "2.5mg"),
    ("lisinopril",          "5mg"),
    ("lisinopril",          "10mg"),
    ("lisinopril",          "20mg"),
    ("lisinopril",          "40mg"),
    ("enalapril",           "5mg"),
    ("enalapril",           "10mg"),
    ("enalapril",           "20mg"),
    ("ramipril",            "2.5mg"),
    ("ramipril",            "5mg"),
    ("ramipril",            "10mg"),
    ("benazepril",          "10mg"),
    ("benazepril",          "20mg"),
    ("quinapril",           "10mg"),
    ("quinapril",           "20mg"),
    ("fosinopril",          "10mg"),
    ("fosinopril",          "20mg"),
    # ARBs
    ("losartan",            "25mg"),
    ("losartan",            "50mg"),
    ("losartan",            "100mg"),
    ("valsartan",           "80mg"),
    ("valsartan",           "160mg"),
    ("valsartan",           "320mg"),
    ("olmesartan",          "20mg"),
    ("olmesartan",          "40mg"),
    ("irbesartan",          "75mg"),
    ("irbesartan",          "150mg"),
    ("irbesartan",          "300mg"),
    ("candesartan",         "8mg"),
    ("candesartan",         "16mg"),
    ("candesartan",         "32mg"),
    ("telmisartan",         "40mg"),
    ("telmisartan",         "80mg"),
    # Beta Blockers
    ("metoprolol",          "25mg"),
    ("metoprolol",          "50mg"),
    ("metoprolol",          "100mg"),
    ("metoprolol",          "200mg"),
    ("atenolol",            "25mg"),
    ("atenolol",            "50mg"),
    ("atenolol",            "100mg"),
    ("carvedilol",          "3.125mg"),
    ("carvedilol",          "6.25mg"),
    ("carvedilol",          "12.5mg"),
    ("carvedilol",          "25mg"),
    ("bisoprolol",          "2.5mg"),
    ("bisoprolol",          "5mg"),
    ("bisoprolol",          "10mg"),
    ("propranolol",         "10mg"),
    ("propranolol",         "20mg"),
    ("propranolol",         "40mg"),
    ("propranolol",         "80mg"),
    ("nebivolol",           "2.5mg"),
    ("nebivolol",           "5mg"),
    ("nebivolol",           "10mg"),
    # Calcium Channel Blockers
    ("amlodipine",          "2.5mg"),
    ("amlodipine",          "5mg"),
    ("amlodipine",          "10mg"),
    ("diltiazem",           "120mg"),
    ("diltiazem",           "180mg"),
    ("diltiazem",           "240mg"),
    ("diltiazem",           "300mg"),
    ("nifedipine",          "30mg"),
    ("nifedipine",          "60mg"),
    ("nifedipine",          "90mg"),
    ("verapamil",           "120mg"),
    ("verapamil",           "180mg"),
    ("verapamil",           "240mg"),
    # Diabetes
    ("metformin",           "500mg"),
    ("metformin",           "850mg"),
    ("metformin",           "1000mg"),
    ("glipizide",           "5mg"),
    ("glipizide",           "10mg"),
    ("glyburide",           "2.5mg"),
    ("glyburide",           "5mg"),
    ("glimepiride",         "1mg"),
    ("glimepiride",         "2mg"),
    ("glimepiride",         "4mg"),
    ("pioglitazone",        "15mg"),
    ("pioglitazone",        "30mg"),
    ("pioglitazone",        "45mg"),
    ("sitagliptin",         "25mg"),
    ("sitagliptin",         "50mg"),
    ("sitagliptin",         "100mg"),
    # Thyroid
    ("levothyroxine",       "25mcg"),
    ("levothyroxine",       "50mcg"),
    ("levothyroxine",       "75mcg"),
    ("levothyroxine",       "88mcg"),
    ("levothyroxine",       "100mcg"),
    ("levothyroxine",       "112mcg"),
    ("levothyroxine",       "125mcg"),
    ("levothyroxine",       "137mcg"),
    ("levothyroxine",       "150mcg"),
    ("levothyroxine",       "175mcg"),
    ("levothyroxine",       "200mcg"),
    # Diuretics
    ("hydrochlorothiazide", "12.5mg"),
    ("hydrochlorothiazide", "25mg"),
    ("hydrochlorothiazide", "50mg"),
    ("furosemide",          "20mg"),
    ("furosemide",          "40mg"),
    ("furosemide",          "80mg"),
    ("spironolactone",      "25mg"),
    ("spironolactone",      "50mg"),
    ("spironolactone",      "100mg"),
    ("chlorthalidone",      "25mg"),
    ("chlorthalidone",      "50mg"),
    ("triamterene",         "50mg"),
    ("triamterene",         "100mg"),
    ("torsemide",           "5mg"),
    ("torsemide",           "10mg"),
    ("torsemide",           "20mg"),
    ("torsemide",           "100mg"),
    # PPIs / GI
    ("omeprazole",          "10mg"),
    ("omeprazole",          "20mg"),
    ("omeprazole",          "40mg"),
    ("pantoprazole",        "20mg"),
    ("pantoprazole",        "40mg"),
    ("esomeprazole",        "20mg"),
    ("esomeprazole",        "40mg"),
    ("lansoprazole",        "15mg"),
    ("lansoprazole",        "30mg"),
    ("rabeprazole",         "20mg"),
    ("famotidine",          "20mg"),
    ("famotidine",          "40mg"),
    ("ranitidine",          "150mg"),
    ("ranitidine",          "300mg"),
    # Antidepressants / Psych
    ("sertraline",          "25mg"),
    ("sertraline",          "50mg"),
    ("sertraline",          "100mg"),
    ("fluoxetine",          "10mg"),
    ("fluoxetine",          "20mg"),
    ("fluoxetine",          "40mg"),
    ("escitalopram",        "5mg"),
    ("escitalopram",        "10mg"),
    ("escitalopram",        "20mg"),
    ("citalopram",          "10mg"),
    ("citalopram",          "20mg"),
    ("citalopram",          "40mg"),
    ("paroxetine",          "10mg"),
    ("paroxetine",          "20mg"),
    ("paroxetine",          "30mg"),
    ("paroxetine",          "40mg"),
    ("venlafaxine",         "37.5mg"),
    ("venlafaxine",         "75mg"),
    ("venlafaxine",         "150mg"),
    ("duloxetine",          "20mg"),
    ("duloxetine",          "30mg"),
    ("duloxetine",          "60mg"),
    ("bupropion",           "75mg"),
    ("bupropion",           "100mg"),
    ("bupropion",           "150mg"),
    ("bupropion",           "200mg"),
    ("bupropion",           "300mg"),
    ("mirtazapine",         "7.5mg"),
    ("mirtazapine",         "15mg"),
    ("mirtazapine",         "30mg"),
    ("mirtazapine",         "45mg"),
    ("trazodone",           "50mg"),
    ("trazodone",           "100mg"),
    ("trazodone",           "150mg"),
    ("amitriptyline",       "10mg"),
    ("amitriptyline",       "25mg"),
    ("amitriptyline",       "50mg"),
    ("amitriptyline",       "75mg"),
    ("amitriptyline",       "100mg"),
    # Anxiety / Sleep
    ("alprazolam",          "0.25mg"),
    ("alprazolam",          "0.5mg"),
    ("alprazolam",          "1mg"),
    ("alprazolam",          "2mg"),
    ("clonazepam",          "0.5mg"),
    ("clonazepam",          "1mg"),
    ("clonazepam",          "2mg"),
    ("lorazepam",           "0.5mg"),
    ("lorazepam",           "1mg"),
    ("lorazepam",           "2mg"),
    ("diazepam",            "2mg"),
    ("diazepam",            "5mg"),
    ("diazepam",            "10mg"),
    ("buspirone",           "5mg"),
    ("buspirone",           "10mg"),
    ("buspirone",           "15mg"),
    ("buspirone",           "30mg"),
    ("zolpidem",            "5mg"),
    ("zolpidem",            "10mg"),
    # Anticonvulsants
    ("gabapentin",          "100mg"),
    ("gabapentin",          "300mg"),
    ("gabapentin",          "400mg"),
    ("gabapentin",          "600mg"),
    ("gabapentin",          "800mg"),
    ("pregabalin",          "25mg"),
    ("pregabalin",          "50mg"),
    ("pregabalin",          "75mg"),
    ("pregabalin",          "100mg"),
    ("pregabalin",          "150mg"),
    ("pregabalin",          "200mg"),
    ("pregabalin",          "225mg"),
    ("pregabalin",          "300mg"),
    ("topiramate",          "25mg"),
    ("topiramate",          "50mg"),
    ("topiramate",          "100mg"),
    ("topiramate",          "200mg"),
    ("lamotrigine",         "25mg"),
    ("lamotrigine",         "50mg"),
    ("lamotrigine",         "100mg"),
    ("lamotrigine",         "150mg"),
    ("lamotrigine",         "200mg"),
    ("levetiracetam",       "250mg"),
    ("levetiracetam",       "500mg"),
    ("levetiracetam",       "750mg"),
    ("levetiracetam",       "1000mg"),
    ("valproic acid",       "250mg"),
    ("valproic acid",       "500mg"),
    ("carbamazepine",       "100mg"),
    ("carbamazepine",       "200mg"),
    ("carbamazepine",       "400mg"),
    # Pain / Muscle
    ("cyclobenzaprine",     "5mg"),
    ("cyclobenzaprine",     "7.5mg"),
    ("cyclobenzaprine",     "10mg"),
    ("baclofen",            "5mg"),
    ("baclofen",            "10mg"),
    ("baclofen",            "20mg"),
    ("methocarbamol",       "500mg"),
    ("methocarbamol",       "750mg"),
    ("carisoprodol",        "250mg"),
    ("carisoprodol",        "350mg"),
    ("tramadol",            "50mg"),
    ("tramadol",            "100mg"),
    ("meloxicam",           "7.5mg"),
    ("meloxicam",           "15mg"),
    ("naproxen",            "220mg"),
    ("naproxen",            "250mg"),
    ("naproxen",            "375mg"),
    ("naproxen",            "500mg"),
    ("ibuprofen",           "200mg"),
    ("ibuprofen",           "400mg"),
    ("ibuprofen",           "600mg"),
    ("ibuprofen",           "800mg"),
    ("celecoxib",           "100mg"),
    ("celecoxib",           "200mg"),
    ("celecoxib",           "400mg"),
    # Antibiotics
    ("amoxicillin",         "250mg"),
    ("amoxicillin",         "500mg"),
    ("amoxicillin",         "875mg"),
    ("amoxicillin-clavulanate", "500mg"),
    ("amoxicillin-clavulanate", "875mg"),
    ("azithromycin",        "250mg"),
    ("azithromycin",        "500mg"),
    ("doxycycline",         "50mg"),
    ("doxycycline",         "100mg"),
    ("doxycycline",         "150mg"),
    ("doxycycline",         "200mg"),
    ("ciprofloxacin",       "250mg"),
    ("ciprofloxacin",       "500mg"),
    ("ciprofloxacin",       "750mg"),
    ("levofloxacin",        "250mg"),
    ("levofloxacin",        "500mg"),
    ("levofloxacin",        "750mg"),
    ("cephalexin",          "250mg"),
    ("cephalexin",          "500mg"),
    ("cephalexin",          "750mg"),
    ("trimethoprim-sulfamethoxazole", "80mg"),
    ("trimethoprim-sulfamethoxazole", "160mg"),
    ("clindamycin",         "150mg"),
    ("clindamycin",         "300mg"),
    ("clindamycin",         "450mg"),
    ("metronidazole",       "250mg"),
    ("metronidazole",       "500mg"),
    ("nitrofurantoin",      "50mg"),
    ("nitrofurantoin",      "100mg"),
    # Respiratory / Allergy
    ("montelukast",         "4mg"),
    ("montelukast",         "5mg"),
    ("montelukast",         "10mg"),
    ("cetirizine",          "5mg"),
    ("cetirizine",          "10mg"),
    ("loratadine",          "10mg"),
    ("fexofenadine",        "60mg"),
    ("fexofenadine",        "120mg"),
    ("fexofenadine",        "180mg"),
    ("prednisone",          "1mg"),
    ("prednisone",          "5mg"),
    ("prednisone",          "10mg"),
    ("prednisone",          "20mg"),
    ("prednisone",          "50mg"),
    ("methylprednisolone",  "4mg"),
    ("methylprednisolone",  "8mg"),
    ("methylprednisolone",  "16mg"),
    ("methylprednisolone",  "32mg"),
    # ADHD
    ("amphetamine salts",   "5mg"),
    ("amphetamine salts",   "10mg"),
    ("amphetamine salts",   "15mg"),
    ("amphetamine salts",   "20mg"),
    ("amphetamine salts",   "25mg"),
    ("amphetamine salts",   "30mg"),
    ("methylphenidate",     "5mg"),
    ("methylphenidate",     "10mg"),
    ("methylphenidate",     "20mg"),
    ("methylphenidate",     "36mg"),
    ("methylphenidate",     "54mg"),
    ("atomoxetine",         "10mg"),
    ("atomoxetine",         "18mg"),
    ("atomoxetine",         "25mg"),
    ("atomoxetine",         "40mg"),
    ("atomoxetine",         "60mg"),
    ("atomoxetine",         "80mg"),
    ("atomoxetine",         "100mg"),
    # Anticoagulants
    ("warfarin",            "1mg"),
    ("warfarin",            "2mg"),
    ("warfarin",            "2.5mg"),
    ("warfarin",            "3mg"),
    ("warfarin",            "4mg"),
    ("warfarin",            "5mg"),
    ("warfarin",            "6mg"),
    ("warfarin",            "7.5mg"),
    ("warfarin",            "10mg"),
    ("rivaroxaban",         "10mg"),
    ("rivaroxaban",         "15mg"),
    ("rivaroxaban",         "20mg"),
    ("apixaban",            "2.5mg"),
    ("apixaban",            "5mg"),
    ("clopidogrel",         "75mg"),
    ("clopidogrel",         "300mg"),
    # Cardiac
    ("digoxin",             "0.125mg"),
    ("digoxin",             "0.25mg"),
    ("isosorbide mononitrate", "30mg"),
    ("isosorbide mononitrate", "60mg"),
    ("isosorbide dinitrate", "10mg"),
    ("isosorbide dinitrate", "20mg"),
    ("hydralazine",         "10mg"),
    ("hydralazine",         "25mg"),
    ("hydralazine",         "50mg"),
    ("hydralazine",         "100mg"),
    ("amiodarone",          "100mg"),
    ("amiodarone",          "200mg"),
    ("amiodarone",          "400mg"),
    ("dronedarone",         "400mg"),
    # Opioids
    ("oxycodone",           "5mg"),
    ("oxycodone",           "10mg"),
    ("oxycodone",           "15mg"),
    ("oxycodone",           "20mg"),
    ("oxycodone",           "30mg"),
    ("hydrocodone",         "5mg"),
    ("hydrocodone",         "7.5mg"),
    ("hydrocodone",         "10mg"),
    ("morphine",            "15mg"),
    ("morphine",            "30mg"),
    ("codeine",             "15mg"),
    ("codeine",             "30mg"),
    ("codeine",             "60mg"),
    ("buprenorphine",       "2mg"),
    ("buprenorphine",       "8mg"),
    # Antipsychotics
    ("quetiapine",          "25mg"),
    ("quetiapine",          "50mg"),
    ("quetiapine",          "100mg"),
    ("quetiapine",          "200mg"),
    ("quetiapine",          "300mg"),
    ("quetiapine",          "400mg"),
    ("aripiprazole",        "2mg"),
    ("aripiprazole",        "5mg"),
    ("aripiprazole",        "10mg"),
    ("aripiprazole",        "15mg"),
    ("aripiprazole",        "20mg"),
    ("aripiprazole",        "30mg"),
    ("olanzapine",          "2.5mg"),
    ("olanzapine",          "5mg"),
    ("olanzapine",          "7.5mg"),
    ("olanzapine",          "10mg"),
    ("olanzapine",          "15mg"),
    ("olanzapine",          "20mg"),
    ("risperidone",         "0.5mg"),
    ("risperidone",         "1mg"),
    ("risperidone",         "2mg"),
    ("risperidone",         "3mg"),
    ("risperidone",         "4mg"),
    ("haloperidol",         "0.5mg"),
    ("haloperidol",         "1mg"),
    ("haloperidol",         "2mg"),
    ("haloperidol",         "5mg"),
    ("haloperidol",         "10mg"),
    ("lithium",             "150mg"),
    ("lithium",             "300mg"),
    ("lithium",             "600mg"),
]

# ─────────────────────────────────────────────────────────────────────────────
# TIER 2 — WEEKLY REFRESH
# ~500 additional drug/strength combos
# ─────────────────────────────────────────────────────────────────────────────

TIER_2_WEEKLY = [
    # GLP-1 / newer diabetes
    ("semaglutide",         "0.25mg"),
    ("semaglutide",         "0.5mg"),
    ("semaglutide",         "1mg"),
    ("semaglutide",         "2mg"),
    ("liraglutide",         "0.6mg"),
    ("liraglutide",         "1.2mg"),
    ("liraglutide",         "1.8mg"),
    ("dulaglutide",         "0.75mg"),
    ("dulaglutide",         "1.5mg"),
    ("empagliflozin",       "10mg"),
    ("empagliflozin",       "25mg"),
    ("dapagliflozin",       "5mg"),
    ("dapagliflozin",       "10mg"),
    ("canagliflozin",       "100mg"),
    ("canagliflozin",       "300mg"),
    ("linagliptin",         "5mg"),
    ("saxagliptin",         "2.5mg"),
    ("saxagliptin",         "5mg"),
    ("alogliptin",          "6.25mg"),
    ("alogliptin",          "12.5mg"),
    ("alogliptin",          "25mg"),
    # Alzheimer's
    ("donepezil",           "5mg"),
    ("donepezil",           "10mg"),
    ("donepezil",           "23mg"),
    ("memantine",           "5mg"),
    ("memantine",           "10mg"),
    ("rivastigmine",        "1.5mg"),
    ("rivastigmine",        "3mg"),
    ("rivastigmine",        "4.5mg"),
    ("rivastigmine",        "6mg"),
    ("galantamine",         "4mg"),
    ("galantamine",         "8mg"),
    ("galantamine",         "12mg"),
    # HIV
    ("tenofovir",           "300mg"),
    ("emtricitabine",       "200mg"),
    ("abacavir",            "300mg"),
    ("lamivudine",          "150mg"),
    ("lamivudine",          "300mg"),
    ("dolutegravir",        "50mg"),
    ("raltegravir",         "400mg"),
    ("efavirenz",           "200mg"),
    ("efavirenz",           "600mg"),
    # Hepatitis C
    ("sofosbuvir",          "400mg"),
    ("ribavirin",           "200mg"),
    ("ribavirin",           "400mg"),
    # Osteoporosis
    ("alendronate",         "5mg"),
    ("alendronate",         "10mg"),
    ("alendronate",         "35mg"),
    ("alendronate",         "70mg"),
    ("risedronate",         "5mg"),
    ("risedronate",         "35mg"),
    ("ibandronate",         "150mg"),
    ("raloxifene",          "60mg"),
    # Gout
    ("allopurinol",         "100mg"),
    ("allopurinol",         "300mg"),
    ("febuxostat",          "40mg"),
    ("febuxostat",          "80mg"),
    ("colchicine",          "0.6mg"),
    ("probenecid",          "500mg"),
    # Urinary
    ("tamsulosin",          "0.4mg"),
    ("silodosin",           "4mg"),
    ("silodosin",           "8mg"),
    ("alfuzosin",           "10mg"),
    ("doxazosin",           "1mg"),
    ("doxazosin",           "2mg"),
    ("doxazosin",           "4mg"),
    ("doxazosin",           "8mg"),
    ("terazosin",           "1mg"),
    ("terazosin",           "2mg"),
    ("terazosin",           "5mg"),
    ("terazosin",           "10mg"),
    ("finasteride",         "1mg"),
    ("finasteride",         "5mg"),
    ("dutasteride",         "0.5mg"),
    ("oxybutynin",          "2.5mg"),
    ("oxybutynin",          "5mg"),
    ("oxybutynin",          "10mg"),
    ("tolterodine",         "1mg"),
    ("tolterodine",         "2mg"),
    ("solifenacin",         "5mg"),
    ("solifenacin",         "10mg"),
    ("mirabegron",          "25mg"),
    ("mirabegron",          "50mg"),
    # Erectile Dysfunction
    ("sildenafil",          "20mg"),
    ("sildenafil",          "25mg"),
    ("sildenafil",          "50mg"),
    ("sildenafil",          "100mg"),
    ("tadalafil",           "2.5mg"),
    ("tadalafil",           "5mg"),
    ("tadalafil",           "10mg"),
    ("tadalafil",           "20mg"),
    ("vardenafil",          "5mg"),
    ("vardenafil",          "10mg"),
    ("vardenafil",          "20mg"),
    # Migraine
    ("sumatriptan",         "25mg"),
    ("sumatriptan",         "50mg"),
    ("sumatriptan",         "100mg"),
    ("rizatriptan",         "5mg"),
    ("rizatriptan",         "10mg"),
    ("zolmitriptan",        "2.5mg"),
    ("zolmitriptan",        "5mg"),
    ("eletriptan",          "20mg"),
    ("eletriptan",          "40mg"),
    ("naratriptan",         "1mg"),
    ("naratriptan",         "2.5mg"),
    ("topiramate",          "25mg"),
    ("topiramate",          "50mg"),
    ("amitriptyline",       "10mg"),
    ("amitriptyline",       "25mg"),
    ("propranolol",         "40mg"),
    ("propranolol",         "80mg"),
    ("verapamil",           "120mg"),
    ("verapamil",           "240mg"),
    # Antivirals
    ("acyclovir",           "200mg"),
    ("acyclovir",           "400mg"),
    ("acyclovir",           "800mg"),
    ("valacyclovir",        "500mg"),
    ("valacyclovir",        "1000mg"),
    ("famciclovir",         "125mg"),
    ("famciclovir",         "250mg"),
    ("famciclovir",         "500mg"),
    ("oseltamivir",         "30mg"),
    ("oseltamivir",         "45mg"),
    ("oseltamivir",         "75mg"),
    # Antifungals
    ("fluconazole",         "50mg"),
    ("fluconazole",         "100mg"),
    ("fluconazole",         "150mg"),
    ("fluconazole",         "200mg"),
    ("itraconazole",        "100mg"),
    ("terbinafine",         "250mg"),
    ("ketoconazole",        "200mg"),
    # Eye Drops (oral where applicable)
    ("acetazolamide",       "125mg"),
    ("acetazolamide",       "250mg"),
    ("methazolamide",       "25mg"),
    ("methazolamide",       "50mg"),
    # Immunosuppressants
    ("methotrexate",        "2.5mg"),
    ("methotrexate",        "5mg"),
    ("methotrexate",        "7.5mg"),
    ("methotrexate",        "10mg"),
    ("methotrexate",        "15mg"),
    ("azathioprine",        "25mg"),
    ("azathioprine",        "50mg"),
    ("mycophenolate",       "250mg"),
    ("mycophenolate",       "500mg"),
    ("hydroxychloroquine",  "200mg"),
    ("hydroxychloroquine",  "400mg"),
    ("leflunomide",         "10mg"),
    ("leflunomide",         "20mg"),
    # Thyroid (additional)
    ("methimazole",         "5mg"),
    ("methimazole",         "10mg"),
    ("propylthiouracil",    "50mg"),
    ("liothyronine",        "5mcg"),
    ("liothyronine",        "25mcg"),
    ("liothyronine",        "50mcg"),
    # Hormones / Contraceptives
    ("norethindrone",       "0.35mg"),
    ("norethindrone",       "5mg"),
    ("medroxyprogesterone", "2.5mg"),
    ("medroxyprogesterone", "5mg"),
    ("medroxyprogesterone", "10mg"),
    ("estradiol",           "0.5mg"),
    ("estradiol",           "1mg"),
    ("estradiol",           "2mg"),
    ("conjugated estrogens","0.3mg"),
    ("conjugated estrogens","0.45mg"),
    ("conjugated estrogens","0.625mg"),
    ("conjugated estrogens","0.9mg"),
    ("conjugated estrogens","1.25mg"),
    ("testosterone",        "50mg"),
    ("testosterone",        "100mg"),
    ("testosterone",        "200mg"),
    # Antiplatelets / Blood
    ("aspirin",             "81mg"),
    ("aspirin",             "325mg"),
    ("ticagrelor",          "60mg"),
    ("ticagrelor",          "90mg"),
    ("prasugrel",           "5mg"),
    ("prasugrel",           "10mg"),
    ("cilostazol",          "50mg"),
    ("cilostazol",          "100mg"),
    # Nausea
    ("ondansetron",         "4mg"),
    ("ondansetron",         "8mg"),
    ("promethazine",        "12.5mg"),
    ("promethazine",        "25mg"),
    ("promethazine",        "50mg"),
    ("metoclopramide",      "5mg"),
    ("metoclopramide",      "10mg"),
    ("prochlorperazine",    "5mg"),
    ("prochlorperazine",    "10mg"),
    ("scopolamine",         "1.5mg"),
    # Smoking cessation
    ("varenicline",         "0.5mg"),
    ("varenicline",         "1mg"),
    ("bupropion",           "150mg"),
    ("nicotine",            "2mg"),
    ("nicotine",            "4mg"),
    # Weight / Obesity
    ("phentermine",         "8mg"),
    ("phentermine",         "15mg"),
    ("phentermine",         "30mg"),
    ("phentermine",         "37.5mg"),
    ("orlistat",            "60mg"),
    ("orlistat",            "120mg"),
    ("topiramate",          "25mg"),
    ("naltrexone",          "50mg"),
    # Dermatology (oral)
    ("isotretinoin",        "10mg"),
    ("isotretinoin",        "20mg"),
    ("isotretinoin",        "30mg"),
    ("isotretinoin",        "40mg"),
    ("doxycycline",         "40mg"),
    ("minocycline",         "50mg"),
    ("minocycline",         "75mg"),
    ("minocycline",         "100mg"),
    ("spironolactone",      "25mg"),
    ("spironolactone",      "50mg"),
    ("spironolactone",      "100mg"),
    # Iron / Vitamins
    ("ferrous sulfate",     "325mg"),
    ("ferrous gluconate",   "325mg"),
    ("folic acid",          "1mg"),
    ("folic acid",          "5mg"),
    ("cyanocobalamin",      "100mcg"),
    ("cyanocobalamin",      "500mcg"),
    ("cyanocobalamin",      "1000mcg"),
    ("cholecalciferol",     "1000iu"),
    ("cholecalciferol",     "2000iu"),
    ("cholecalciferol",     "5000iu"),
    # Fibromyalgia / Neuropathy
    ("milnacipran",         "12.5mg"),
    ("milnacipran",         "25mg"),
    ("milnacipran",         "50mg"),
    ("milnacipran",         "100mg"),
    # Immunology / Rare
    ("tacrolimus",          "0.5mg"),
    ("tacrolimus",          "1mg"),
    ("tacrolimus",          "5mg"),
    ("cyclosporine",        "25mg"),
    ("cyclosporine",        "50mg"),
    ("cyclosporine",        "100mg"),
    # Parkinson's
    ("carbidopa-levodopa",  "10-100mg"),
    ("carbidopa-levodopa",  "25-100mg"),
    ("carbidopa-levodopa",  "25-250mg"),
    ("pramipexole",         "0.125mg"),
    ("pramipexole",         "0.25mg"),
    ("pramipexole",         "0.5mg"),
    ("pramipexole",         "0.75mg"),
    ("pramipexole",         "1mg"),
    ("pramipexole",         "1.5mg"),
    ("ropinirole",          "0.25mg"),
    ("ropinirole",          "0.5mg"),
    ("ropinirole",          "1mg"),
    ("ropinirole",          "2mg"),
    ("ropinirole",          "3mg"),
    ("ropinirole",          "4mg"),
    ("ropinirole",          "5mg"),
    ("entacapone",          "200mg"),
    ("rasagiline",          "0.5mg"),
    ("rasagiline",          "1mg"),
    ("selegiline",          "5mg"),
    # Multiple Sclerosis
    ("dimethyl fumarate",   "120mg"),
    ("dimethyl fumarate",   "240mg"),
    ("teriflunomide",       "7mg"),
    ("teriflunomide",       "14mg"),
    ("fingolimod",          "0.5mg"),
    # Pulmonary Hypertension
    ("sildenafil",          "20mg"),
    ("bosentan",            "62.5mg"),
    ("bosentan",            "125mg"),
    ("ambrisentan",         "5mg"),
    ("ambrisentan",         "10mg"),
    # Additional antibiotics
    ("moxifloxacin",        "400mg"),
    ("linezolid",           "400mg"),
    ("linezolid",           "600mg"),
    ("vancomycin",          "125mg"),
    ("vancomycin",          "250mg"),
    ("rifampin",            "150mg"),
    ("rifampin",            "300mg"),
    ("ethambutol",          "100mg"),
    ("ethambutol",          "400mg"),
    ("isoniazid",           "100mg"),
    ("isoniazid",           "300mg"),
    ("pyrazinamide",        "500mg"),
    ("sulfasalazine",       "500mg"),
    ("chloroquine",         "250mg"),
    ("chloroquine",         "500mg"),
    # Supplements with clinical significance
    ("magnesium oxide",     "250mg"),
    ("magnesium oxide",     "400mg"),
    ("potassium chloride",  "8meq"),
    ("potassium chloride",  "10meq"),
    ("potassium chloride",  "20meq"),
    ("zinc sulfate",        "110mg"),
    ("zinc sulfate",        "220mg"),
    # Additional cardio
    ("ivabradine",          "2.5mg"),
    ("ivabradine",          "5mg"),
    ("ivabradine",          "7.5mg"),
    ("ranolazine",          "500mg"),
    ("ranolazine",          "1000mg"),
    ("sacubitril-valsartan","24-26mg"),
    ("sacubitril-valsartan","49-51mg"),
    ("sacubitril-valsartan","97-103mg"),
    ("eplerenone",          "25mg"),
    ("eplerenone",          "50mg"),
]

# ─────────────────────────────────────────────────────────────────────────────
# TIER 3 — MONTHLY REFRESH
# ~500 additional specialty / low-volume combos
# ─────────────────────────────────────────────────────────────────────────────

TIER_3_MONTHLY = [
    # Oncology (oral)
    ("imatinib",            "100mg"),
    ("imatinib",            "400mg"),
    ("erlotinib",           "25mg"),
    ("erlotinib",           "100mg"),
    ("erlotinib",           "150mg"),
    ("lapatinib",           "250mg"),
    ("sunitinib",           "12.5mg"),
    ("sunitinib",           "25mg"),
    ("sunitinib",           "37.5mg"),
    ("sunitinib",           "50mg"),
    ("sorafenib",           "200mg"),
    ("temozolomide",        "5mg"),
    ("temozolomide",        "20mg"),
    ("temozolomide",        "100mg"),
    ("temozolomide",        "140mg"),
    ("temozolomide",        "180mg"),
    ("temozolomide",        "250mg"),
    ("capecitabine",        "150mg"),
    ("capecitabine",        "500mg"),
    ("cyclophosphamide",    "25mg"),
    ("cyclophosphamide",    "50mg"),
    ("melphalan",           "2mg"),
    ("chlorambucil",        "2mg"),
    ("busulfan",            "2mg"),
    ("hydroxyurea",         "200mg"),
    ("hydroxyurea",         "300mg"),
    ("hydroxyurea",         "400mg"),
    ("mercaptopurine",      "50mg"),
    ("thioguanine",         "40mg"),
    ("abiraterone",         "250mg"),
    ("abiraterone",         "500mg"),
    ("enzalutamide",        "40mg"),
    ("ibrutinib",           "140mg"),
    ("idelalisib",          "100mg"),
    ("idelalisib",          "150mg"),
    ("venetoclax",          "10mg"),
    ("venetoclax",          "50mg"),
    ("venetoclax",          "100mg"),
    ("olaparib",            "100mg"),
    ("olaparib",            "150mg"),
    ("niraparib",           "100mg"),
    ("rucaparib",           "200mg"),
    ("rucaparib",           "300mg"),
    # Cystic Fibrosis
    ("ivacaftor",           "150mg"),
    ("lumacaftor-ivacaftor","100-125mg"),
    ("lumacaftor-ivacaftor","200-125mg"),
    ("tezacaftor-ivacaftor","100-150mg"),
    ("elexacaftor-tezacaftor-ivacaftor", "100-50-75mg"),
    # Rare diseases
    ("eculizumab",          "300mg"),
    ("migalastat",          "123mg"),
    ("cerliponase alfa",    "300mg"),
    ("eliglustat",          "84mg"),
    ("miglustat",           "100mg"),
    # Psychiatry specialty
    ("clozapine",           "25mg"),
    ("clozapine",           "50mg"),
    ("clozapine",           "100mg"),
    ("clozapine",           "200mg"),
    ("clozapine",           "250mg"),
    ("ziprasidone",         "20mg"),
    ("ziprasidone",         "40mg"),
    ("ziprasidone",         "60mg"),
    ("ziprasidone",         "80mg"),
    ("lurasidone",          "20mg"),
    ("lurasidone",          "40mg"),
    ("lurasidone",          "60mg"),
    ("lurasidone",          "80mg"),
    ("lurasidone",          "120mg"),
    ("paliperidone",        "1.5mg"),
    ("paliperidone",        "3mg"),
    ("paliperidone",        "6mg"),
    ("paliperidone",        "9mg"),
    ("asenapine",           "2.5mg"),
    ("asenapine",           "5mg"),
    ("asenapine",           "10mg"),
    ("brexpiprazole",       "0.5mg"),
    ("brexpiprazole",       "1mg"),
    ("brexpiprazole",       "2mg"),
    ("brexpiprazole",       "3mg"),
    ("brexpiprazole",       "4mg"),
    ("cariprazine",         "1.5mg"),
    ("cariprazine",         "3mg"),
    ("cariprazine",         "4.5mg"),
    ("cariprazine",         "6mg"),
    # Addiction medicine
    ("naltrexone",          "50mg"),
    ("acamprosate",         "333mg"),
    ("disulfiram",          "250mg"),
    ("disulfiram",          "500mg"),
    ("methadone",           "5mg"),
    ("methadone",           "10mg"),
    ("buprenorphine-naloxone", "2-0.5mg"),
    ("buprenorphine-naloxone", "8-2mg"),
    ("buprenorphine-naloxone", "12-3mg"),
    # Endocrinology specialty
    ("octreotide",          "50mcg"),
    ("bromocriptine",       "0.8mg"),
    ("bromocriptine",       "2.5mg"),
    ("cabergoline",         "0.5mg"),
    ("cabergoline",         "1mg"),
    ("fludrocortisone",     "0.1mg"),
    ("hydrocortisone",      "5mg"),
    ("hydrocortisone",      "10mg"),
    ("hydrocortisone",      "20mg"),
    ("desmopressin",        "0.1mg"),
    ("desmopressin",        "0.2mg"),
    ("somatropin",          "5mg"),
    ("somatropin",          "10mg"),
    # Pediatric specialty
    ("caffeine citrate",    "20mg"),
    ("ursodiol",            "300mg"),
    ("ursodiol",            "500mg"),
    ("cholestyramine",      "4000mg"),
    ("colesevelam",         "625mg"),
    ("colestipol",          "1000mg"),
    # Ophthalmology oral
    ("carbonic anhydrase",  "25mg"),
    ("pilocarpine",         "5mg"),
    ("pilocarpine",         "7.5mg"),
    # Hemostasis
    ("tranexamic acid",     "500mg"),
    ("aminocaproic acid",   "500mg"),
    ("aminocaproic acid",   "1000mg"),
    # Rheumatology specialty
    ("anakinra",            "100mg"),
    ("colchicine",          "0.6mg"),
    ("pegloticase",         "8mg"),
    ("belimumab",           "200mg"),
    # Gastroparesis / IBD
    ("mesalamine",          "400mg"),
    ("mesalamine",          "500mg"),
    ("mesalamine",          "800mg"),
    ("balsalazide",         "750mg"),
    ("olsalazine",          "250mg"),
    ("budesonide",          "3mg"),
    ("budesonide",          "9mg"),
    # Chronic kidney disease
    ("sevelamer",           "400mg"),
    ("sevelamer",           "800mg"),
    ("lanthanum carbonate", "500mg"),
    ("lanthanum carbonate", "750mg"),
    ("lanthanum carbonate", "1000mg"),
    ("cinacalcet",          "30mg"),
    ("cinacalcet",          "60mg"),
    ("cinacalcet",          "90mg"),
    # Pulmonology specialty
    ("pirfenidone",         "267mg"),
    ("nintedanib",          "100mg"),
    ("nintedanib",          "150mg"),
    ("roflumilast",         "250mcg"),
    ("roflumilast",         "500mcg"),
    # Additional sleep
    ("suvorexant",          "5mg"),
    ("suvorexant",          "10mg"),
    ("suvorexant",          "15mg"),
    ("suvorexant",          "20mg"),
    ("lemborexant",         "5mg"),
    ("lemborexant",         "10mg"),
    ("ramelteon",           "8mg"),
    ("doxepin",             "3mg"),
    ("doxepin",             "6mg"),
    # Neonatal / Pediatric
    ("sildenafil",          "10mg"),
    ("bosentan",            "32mg"),
    ("ambrisentan",         "2.5mg"),
    # Antidiarrheal / Bowel
    ("loperamide",          "2mg"),
    ("diphenoxylate-atropine", "2.5mg"),
    ("rifaximin",           "200mg"),
    ("rifaximin",           "550mg"),
    # Additional pain
    ("tapentadol",          "50mg"),
    ("tapentadol",          "75mg"),
    ("tapentadol",          "100mg"),
    ("tapentadol",          "150mg"),
    ("tapentadol",          "200mg"),
    ("tapentadol",          "250mg"),
    ("ziconotide",          "25mcg"),
    ("buprenorphine",       "5mcg"),
    ("buprenorphine",       "10mcg"),
    ("buprenorphine",       "20mcg"),
    # Additional antiepileptics
    ("brivaracetam",        "10mg"),
    ("brivaracetam",        "25mg"),
    ("brivaracetam",        "50mg"),
    ("brivaracetam",        "75mg"),
    ("brivaracetam",        "100mg"),
    ("lacosamide",          "50mg"),
    ("lacosamide",          "100mg"),
    ("lacosamide",          "150mg"),
    ("lacosamide",          "200mg"),
    ("perampanel",          "2mg"),
    ("perampanel",          "4mg"),
    ("perampanel",          "6mg"),
    ("perampanel",          "8mg"),
    ("perampanel",          "10mg"),
    ("perampanel",          "12mg"),
    ("eslicarbazepine",     "200mg"),
    ("eslicarbazepine",     "400mg"),
    ("eslicarbazepine",     "600mg"),
    ("eslicarbazepine",     "800mg"),
    ("vigabatrin",          "500mg"),
    ("rufinamide",          "200mg"),
    ("rufinamide",          "400mg"),
    ("clobazam",            "5mg"),
    ("clobazam",            "10mg"),
    ("clobazam",            "20mg"),
    # Transplant
    ("sirolimus",           "0.5mg"),
    ("sirolimus",           "1mg"),
    ("sirolimus",           "2mg"),
    ("everolimus",          "0.25mg"),
    ("everolimus",          "0.5mg"),
    ("everolimus",          "0.75mg"),
    ("everolimus",          "1mg"),
    # Additional antiretrovirals
    ("zidovudine",          "100mg"),
    ("zidovudine",          "300mg"),
    ("stavudine",           "15mg"),
    ("stavudine",           "20mg"),
    ("stavudine",           "30mg"),
    ("stavudine",           "40mg"),
    ("didanosine",          "125mg"),
    ("didanosine",          "200mg"),
    ("didanosine",          "250mg"),
    ("didanosine",          "400mg"),
    ("lopinavir-ritonavir", "100-25mg"),
    ("lopinavir-ritonavir", "200-50mg"),
    ("atazanavir",          "100mg"),
    ("atazanavir",          "150mg"),
    ("atazanavir",          "200mg"),
    ("atazanavir",          "300mg"),
    ("darunavir",           "75mg"),
    ("darunavir",           "150mg"),
    ("darunavir",           "400mg"),
    ("darunavir",           "600mg"),
    ("darunavir",           "800mg"),
]


def get_all_drugs():
    """Returns list of (drug_name, strength, tier) for all drugs."""
    result = []
    for drug, strength in TIER_1_DAILY:
        result.append((drug, strength, "daily"))
    for drug, strength in TIER_2_WEEKLY:
        result.append((drug, strength, "weekly"))
    for drug, strength in TIER_3_MONTHLY:
        result.append((drug, strength, "monthly"))
    return result


if __name__ == "__main__":
    all_drugs = get_all_drugs()
    daily   = [d for d in all_drugs if d[2] == "daily"]
    weekly  = [d for d in all_drugs if d[2] == "weekly"]
    monthly = [d for d in all_drugs if d[2] == "monthly"]
    print(f"Tier 1 Daily:   {len(daily)} drug/strength combos")
    print(f"Tier 2 Weekly:  {len(weekly)} drug/strength combos")
    print(f"Tier 3 Monthly: {len(monthly)} drug/strength combos")
    print(f"Total:          {len(all_drugs)} drug/strength combos")

# ─────────────────────────────────────────────────────────────────────────────
# TIER 1 EXPANSION — additional high-volume strengths
# ─────────────────────────────────────────────────────────────────────────────

TIER_1_DAILY_EXTRA = [
    # More statin combos
    ("pitavastatin",        "1mg"),
    ("pitavastatin",        "2mg"),
    ("pitavastatin",        "4mg"),
    # Diuretic combos
    ("bumetanide",          "0.5mg"),
    ("bumetanide",          "1mg"),
    ("bumetanide",          "2mg"),
    ("metolazone",          "2.5mg"),
    ("metolazone",          "5mg"),
    ("metolazone",          "10mg"),
    ("indapamide",          "1.25mg"),
    ("indapamide",          "2.5mg"),
    # More GI
    ("sucralfate",          "1000mg"),
    ("misoprostol",         "100mcg"),
    ("misoprostol",         "200mcg"),
    ("dicyclomine",         "10mg"),
    ("dicyclomine",         "20mg"),
    ("hyoscyamine",         "0.125mg"),
    ("hyoscyamine",         "0.375mg"),
    ("loperamide",          "2mg"),
    ("simethicone",         "80mg"),
    ("simethicone",         "125mg"),
    # More antibiotics
    ("minocycline",         "50mg"),
    ("minocycline",         "75mg"),
    ("minocycline",         "100mg"),
    ("erythromycin",        "250mg"),
    ("erythromycin",        "333mg"),
    ("erythromycin",        "500mg"),
    ("clarithromycin",      "250mg"),
    ("clarithromycin",      "500mg"),
    ("tetracycline",        "250mg"),
    ("tetracycline",        "500mg"),
    ("sulfamethoxazole",    "400mg"),
    ("sulfamethoxazole",    "800mg"),
    ("trimethoprim",        "100mg"),
    ("trimethoprim",        "200mg"),
    ("cefuroxime",          "250mg"),
    ("cefuroxime",          "500mg"),
    ("cefprozil",           "250mg"),
    ("cefprozil",           "500mg"),
    ("cefdinir",            "300mg"),
    ("loracarbef",          "200mg"),
    ("loracarbef",          "400mg"),
    ("penicillin v",        "250mg"),
    ("penicillin v",        "500mg"),
    ("dicloxacillin",       "250mg"),
    ("dicloxacillin",       "500mg"),
    ("cloxacillin",         "250mg"),
    ("cloxacillin",         "500mg"),
    ("ampicillin",          "250mg"),
    ("ampicillin",          "500mg"),
    # Corticosteroids
    ("dexamethasone",       "0.5mg"),
    ("dexamethasone",       "0.75mg"),
    ("dexamethasone",       "1mg"),
    ("dexamethasone",       "1.5mg"),
    ("dexamethasone",       "2mg"),
    ("dexamethasone",       "4mg"),
    ("dexamethasone",       "6mg"),
    ("betamethasone",       "0.6mg"),
    ("triamcinolone",       "4mg"),
    ("triamcinolone",       "8mg"),
    ("cortisone",           "5mg"),
    ("cortisone",           "10mg"),
    ("cortisone",           "25mg"),
    # More pain
    ("ketorolac",           "10mg"),
    ("indomethacin",        "25mg"),
    ("indomethacin",        "50mg"),
    ("indomethacin",        "75mg"),
    ("piroxicam",           "10mg"),
    ("piroxicam",           "20mg"),
    ("sulindac",            "150mg"),
    ("sulindac",            "200mg"),
    ("etodolac",            "200mg"),
    ("etodolac",            "300mg"),
    ("etodolac",            "400mg"),
    ("etodolac",            "500mg"),
    ("etodolac",            "600mg"),
    ("diclofenac",          "25mg"),
    ("diclofenac",          "50mg"),
    ("diclofenac",          "75mg"),
    ("diclofenac",          "100mg"),
    ("flurbiprofen",        "50mg"),
    ("flurbiprofen",        "100mg"),
    ("ketoprofen",          "25mg"),
    ("ketoprofen",          "50mg"),
    ("ketoprofen",          "75mg"),
    ("oxaprozin",           "600mg"),
    ("nabumetone",          "500mg"),
    ("nabumetone",          "750mg"),
    ("diflunisal",          "250mg"),
    ("diflunisal",          "500mg"),
    ("meclofenamate",       "50mg"),
    ("meclofenamate",       "100mg"),
    # More opioids
    ("hydromorphone",       "2mg"),
    ("hydromorphone",       "4mg"),
    ("hydromorphone",       "8mg"),
    ("fentanyl",            "12mcg"),
    ("fentanyl",            "25mcg"),
    ("fentanyl",            "50mcg"),
    ("fentanyl",            "75mcg"),
    ("fentanyl",            "100mcg"),
    ("oxymorphone",         "5mg"),
    ("oxymorphone",         "10mg"),
    ("meperidine",          "50mg"),
    ("meperidine",          "100mg"),
    ("levorphanol",         "2mg"),
    # More psych
    ("nortriptyline",       "10mg"),
    ("nortriptyline",       "25mg"),
    ("nortriptyline",       "50mg"),
    ("nortriptyline",       "75mg"),
    ("imipramine",          "10mg"),
    ("imipramine",          "25mg"),
    ("imipramine",          "50mg"),
    ("desipramine",         "10mg"),
    ("desipramine",         "25mg"),
    ("desipramine",         "50mg"),
    ("desipramine",         "75mg"),
    ("desipramine",         "100mg"),
    ("desipramine",         "150mg"),
    ("clomipramine",        "25mg"),
    ("clomipramine",        "50mg"),
    ("clomipramine",        "75mg"),
    ("doxepin",             "10mg"),
    ("doxepin",             "25mg"),
    ("doxepin",             "50mg"),
    ("doxepin",             "75mg"),
    ("doxepin",             "100mg"),
    ("doxepin",             "150mg"),
    ("fluvoxamine",         "25mg"),
    ("fluvoxamine",         "50mg"),
    ("fluvoxamine",         "100mg"),
    ("maprotiline",         "25mg"),
    ("maprotiline",         "50mg"),
    ("maprotiline",         "75mg"),
    # Antihistamines
    ("diphenhydramine",     "25mg"),
    ("diphenhydramine",     "50mg"),
    ("hydroxyzine",         "10mg"),
    ("hydroxyzine",         "25mg"),
    ("hydroxyzine",         "50mg"),
    ("hydroxyzine",         "100mg"),
    ("cyproheptadine",      "4mg"),
    ("chlorpheniramine",    "4mg"),
    ("chlorpheniramine",    "8mg"),
    ("brompheniramine",     "4mg"),
    ("clemastine",          "1.34mg"),
    ("clemastine",          "2.68mg"),
    ("meclizine",           "12.5mg"),
    ("meclizine",           "25mg"),
    ("dimenhydrinate",      "50mg"),
    # Cardiovascular additional
    ("nitroglycerin",       "0.3mg"),
    ("nitroglycerin",       "0.4mg"),
    ("nitroglycerin",       "0.6mg"),
    ("nitroglycerin",       "2.5mg"),
    ("nitroglycerin",       "6.5mg"),
    ("nitroglycerin",       "9mg"),
    ("prazosin",            "1mg"),
    ("prazosin",            "2mg"),
    ("prazosin",            "5mg"),
    ("clonidine",           "0.1mg"),
    ("clonidine",           "0.2mg"),
    ("clonidine",           "0.3mg"),
    ("methyldopa",          "125mg"),
    ("methyldopa",          "250mg"),
    ("methyldopa",          "500mg"),
    ("reserpine",           "0.1mg"),
    ("reserpine",           "0.25mg"),
    ("guanfacine",          "1mg"),
    ("guanfacine",          "2mg"),
    ("guanfacine",          "3mg"),
    ("guanfacine",          "4mg"),
    ("phenoxybenzamine",    "10mg"),
    ("phentolamine",        "5mg"),
    # Hyperlipidemia additional
    ("niacin",              "500mg"),
    ("niacin",              "750mg"),
    ("niacin",              "1000mg"),
    ("fenofibrate",         "48mg"),
    ("fenofibrate",         "54mg"),
    ("fenofibrate",         "107mg"),
    ("fenofibrate",         "120mg"),
    ("fenofibrate",         "145mg"),
    ("fenofibrate",         "160mg"),
    ("gemfibrozil",         "600mg"),
    ("omega-3 fatty acids", "1000mg"),
    ("omega-3 fatty acids", "4000mg"),
    ("icosapent ethyl",     "1000mg"),
    ("icosapent ethyl",     "4000mg"),
    ("ezetimibe",           "10mg"),
    # More respiratory
    ("theophylline",        "100mg"),
    ("theophylline",        "200mg"),
    ("theophylline",        "300mg"),
    ("theophylline",        "400mg"),
    ("aminophylline",       "100mg"),
    ("aminophylline",       "200mg"),
    ("ipratropium",         "17mcg"),
    ("tiotropium",          "18mcg"),
    ("umeclidinium",        "62.5mcg"),
    ("aclidinium",          "400mcg"),
    ("glycopyrrolate",      "1mg"),
    ("glycopyrrolate",      "2mg"),
    ("roflumilast",         "500mcg"),
    # Antidiabetic additional
    ("nateglinide",         "60mg"),
    ("nateglinide",         "120mg"),
    ("repaglinide",         "0.5mg"),
    ("repaglinide",         "1mg"),
    ("repaglinide",         "2mg"),
    ("acarbose",            "25mg"),
    ("acarbose",            "50mg"),
    ("acarbose",            "100mg"),
    ("miglitol",            "25mg"),
    ("miglitol",            "50mg"),
    ("miglitol",            "100mg"),
]

TIER_1_DAILY.extend(TIER_1_DAILY_EXTRA)


def get_all_drugs():
    """Returns list of (drug_name, strength, tier) for all drugs."""
    result = []
    seen = set()
    for drug, strength in TIER_1_DAILY:
        key = (drug.lower(), strength.lower())
        if key not in seen:
            seen.add(key)
            result.append((drug, strength, "daily"))
    for drug, strength in TIER_2_WEEKLY:
        key = (drug.lower(), strength.lower())
        if key not in seen:
            seen.add(key)
            result.append((drug, strength, "weekly"))
    for drug, strength in TIER_3_MONTHLY:
        key = (drug.lower(), strength.lower())
        if key not in seen:
            seen.add(key)
            result.append((drug, strength, "monthly"))
    return result